//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        protected string author1;      // Данные, содержащиеся в любом объекте класса Man
        protected int id_Author;

        static int maxName = 20;
        public Author()
        {
            this.BookAuthor = new HashSet<BookAuthor>();
        }
    
        public int Id_Author { get; set; }
        public string Author1 {
            get { return author1; }
            set
            {
                if (value.Length > maxName)
                    author1 = Helper.GetName(value.Substring(0, maxName));
                else
                    author1 = Helper.GetName(value);
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookAuthor> BookAuthor { get; set; }
    }
}
