//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookAuthor
    {
        public int Id { get; set; }
        public Nullable<int> Id_Book { get; set; }
        public Nullable<int> Id_Author { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Book Book { get; set; }
    }
}
